### ISSUE TITLE
C22 - Arcade Labeling and Rotation not working

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#109]
Dear Esri-Team,

Software: Collector
Verion  : Build 2284
OS      : iOS 11.4, iPad Air 2

Description:

setup in ArcGIS Pro Arcade labelinig with rotation, and share as a WebMap, when displaying in Collector, the roation of the labeling is ignored

Attached the data and screendumps to reproduce the problem.

Best regards,

Gerhard "Luigi" Trichtl
[C22.zip](https://github.com/doug-m/CollectorAuroraTesting/files/2112682/C22.zip)
[bug.docx](https://github.com/doug-m/CollectorAuroraTesting/files/2112686/bug.docx)

**Comment by Kevin-GIS** [comment]
@trichtl Label rotation from a field doesn't appear to be supported outside of ArcGIS Pro, even with just basic labels w/out arcade. 

Pro screenshot:
![c1](https://user-images.githubusercontent.com/24723464/41680642-11233434-7487-11e8-82b8-4304a3d9cc85.JPG)

AGOL screenshot: (Collector is the same)
![c2](https://user-images.githubusercontent.com/24723464/41680662-1e45fd5e-7487-11e8-9e74-28e49a21d218.JPG)

In Pro, when configuring the labels, you can set different properties for the 'Symbol' or 'Position'. For the 'Symbol' properties, you can set a rotation angle, which looks to be supported in the JSON for the webmap, but not when setting the rotation from a field the JSON doesn't capture that information, which explains why both the AGOL map viewer and Aurora drop the rotation. 

Both the webmap and hosted FS have similar JSON:
![c3](https://user-images.githubusercontent.com/24723464/41680871-b97660d4-7487-11e8-905e-ee395d0c4e69.JPG)

Therefore I am going to mark this issue as closed, since label rotation from a field isn't supported in the webmap/hosted FS. 

Even if I add the hosted FS back into Pro, it displays w/out symbol rotation.

**Comment by trichtl** [comment]
HI Kevin, the label Rotation is just one part, I would log this within ArcGIS Pro, that there Comes at warning, that the Rotation Setting would be dropped.
But there is still one issue with the provided data - the Symbol is not coming through - it's shown correctly in the WebMap, but not within Collector (Online Mode) - should we see this as a separate issue, or handle here as well?

**Comment by Kevin-GIS** [comment]
@trichtl Yes please lets log that as a separate issue.
