### ISSUE TITLE
When downloading pre-planned offline areas, an error is thrown

### ISSUE THREAD

**Issue by sbubka94** [doug-m/CollectorAuroraTesting#150]
### Issue
When downloading pre-planned areas from ArcGIS Online 6.2 BETA, an error is thrown. Download Error : not found

### Expected Behavior
It should download successfully

### Map and Credentials
Reproduced with any map/layer in QA environment (tested on 2 separate maps/feature layers)

### Steps to Reproduce

Create pre-planned map area
http://docdev.arcgis.com/en/arcgis-online/manage-data/take-maps-offline.htm

Attempt to download it from Collector Beta

### Device Information
* Device: iPhone 7+
* OS Version: iOS 11.4

![image1](https://user-images.githubusercontent.com/22916127/41617709-0decad3a-73b6-11e8-8030-c45a1f770974.png)

**Comment by mschenker** [comment]
Sounds like a duplicate to #97

**Comment by yapiyapo** [comment]
This issue occurred for me as well.

**Comment by miaogeng** [comment]
@sbubka94 @mschenker @yapiyapo now you can test preplan with ArcGIS Online production environment  using your own org. If you still see this issue, can you look at ArcGIS Online and see if both replica and basemap created in the map area. From what I have seen, usually either replica is not created or basemap is not.

**Comment by Kevin-GIS** [comment]
Closing this issue as this behavior has been addressed. 

The original issue was likely due to trying to download the area before all of its components were built through AGOL, such as the TPK or the SQLite geodatabase. 

Collector now displays 'Generating...' for any preplanned area that is still getting built and prevents it from getting downloaded until its completed. Once all the necessary components of the offline area have been generated, it should be available for download in Collector.
