### ISSUE TITLE
Failing to create points for some Hosted Feature Services

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#167]
### Issue
I have found that with some of my existing Hosted Feature Services, I am unable to add new point features in Web Maps. A message is displayed under New Feature saying "no valid location".

I have tried changing the symbology, adding to new Web Maps, and a few other minor tweaks. I added the Hydrants Hosted Feature Layer template to the same map and this one works without issue. You can add points manually to the problematic layers without issue.

### Map and Credentials

* Group Name: Collector Holistic 8/21
* Map Name: PointCreationFail

### Steps to Reproduce
1. Use the credentials about to access the Web Map
2. Attempt to create a point for "zion springs"
3. "No valid location" will display under New Feature. Clicking Add Point does nothing
4. Move cursor to manually place point successfully
5. Use the Hydrants layer to successfully add a point at your location

### Device Information
* Device: iphone 6
* OS Version: 11.4.1

![point_fail](https://user-images.githubusercontent.com/15009559/44481400-87969580-a5fa-11e8-8d0d-c1b061af9e6d.PNG)

**Comment by Kevin-GIS** [comment]
Hi @colinlawr when working with the Integrated Receiver and capturing GPS locations using a Z-enabled layer, the location is not valid if it doesn't include a Z value, which the integrated receiver for iOS typically doesn't. 

This is not a problem when using an external receiver since typically all supply a Z value with the location. 

When capturing a manual feature using the same Z-enabled layer, we use the default Z value set at publishing. 

The reason being is because now that Collector supports Z values and for those users who need to capture those Z values, the location isn't valid if the Z value is null. 

Therefore this is expected behavior.
