### ISSUE TITLE
Offline issues  (packaging) Aurora and AGOL

### ISSUE THREAD

**Issue by erikjamesmason** [doug-m/CollectorAuroraTesting#201]
### Issue
Manage Areas, Offline Areas experiencing lag and other difficulties. I tried creating some areas in AGOL for Aurora in a layer, which took variable amount of duration (I even had to make several attempts). The areas showed on Aurora, but would not download and gave several errors. Also, apparently can't manage areas on Aurora? So i was unable to use the map at all since it only shows the areas i made and i was unable to download them. 

### Map and Credentials

* Group Name: JFO Seasonal Counts Collector
* Map Name: JFO Seasonal Counts Master

### Steps to Reproduce

attempting to reproduce, but packaging is taking hours...

Collector4ArcGIS is already invited to the group, the map name is JFO Seasonal Counts Master.

view manage areas on AGOL, and offline areas in Aurora

experience issues.

### Device Information
* Device: windows 10 computer, iPad
* OS Version: 11.4.1

![image](https://user-images.githubusercontent.com/43789112/46434304-c2164680-c6ff-11e8-9ff3-006787b501db.png)

![meh](https://user-images.githubusercontent.com/43789112/46434519-4bc61400-c700-11e8-8271-ce4a23e152bd.png)

**Comment by Kevin-GIS** [comment]
Closing this issue as this behavior has been addressed.

The original issue was likely due to trying to download the area before all of its components were built through AGOL, such as the TPK or the SQLite geodatabase.

Collector now displays 'Generating...' for any preplanned area that is still getting built and prevents it from getting downloaded until its completed. Once all the necessary components of the offline area have been generated, it should be available for download in Collector.
