### ISSUE TITLE
Required Fields

### ISSUE THREAD

**Issue by msmith12345** [doug-m/CollectorAuroraTesting#202]
### Issue
In AGOL, the required fields are not honored.  You can save the point on the map without filling any information into the fields even if the fields were set up to "not allow nulls".   The domains are flagged as required, the fields show the red * after the field name noting the fields were set to "not allow nulls".  The point can be saved on the map and a record is saved to the database even though required fields have been defined. 

### Expected Behavior
I think AGOL should follow the database rules defined.

### Map and Credentials

* Group Name: OSFM DSpace Staging
* Map Name: PREFIRE2019_V2_1_Map

### Steps to Reproduce
Select Map
Click Edit 
Add point on the map
Close pop up
Blank record was saved to the database - Click on the table view to see the blank record was saved to the database.

### Device Information
* Device: Desktop
* OS Version: Windows 

![image](https://user-images.githubusercontent.com/43820465/46432947-639f9700-c704-11e8-9d0b-9471f87797bb.png)

![image](https://user-images.githubusercontent.com/43820465/46432955-69957800-c704-11e8-8cb7-48a763a96ac9.png)

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @msmith12345 

This issue is related to AGOL and not specifically to Collector. I've shared this feedback with the AGOL team. I will go ahead and close this issue.

**Comment by Kevin-GIS** [comment]
@msmith12345 after reviewing the feature service JSON for the PFIS.PREFIRE_2019_PROPERTY layer in AGOL, the template sections displays an empty string value as the default value for the ADDRESSVISIBLE, CITY, etc non-nullable fields. Therefore when attempting to create a new feature in AGOL, it uses that empty string as the value and therefore allows the feature to be submitted. 

This happens when publishing the feature service with non-nullable fields and no default value specified. 

Please review the following blog for more information about this issue and how to address it and remove those empty strings (or 0's for numerical fields) in the template information. 
[Required Fields](https://www.esri.com/arcgis-blog/products/collector/field-mobility/capture-required-information-from-field/)
