### ISSUE TITLE
Map list should display name of web map WITH name of offline area

### ISSUE THREAD

**Issue by psp2k** [doug-m/CollectorAuroraTesting#27]
### Issue
When using an offline area (as 'Current'), the name displayed is just the name of the offline area

### Expected Behavior
I would think you would want to always include the name of the web map especially when you can't edit the name of the offline area. In other words, I think you'd want to display:
My Webmap
Area 1
..or..
My Webmap: Area 1

### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device:
* OS Version:

**Comment by trichtl** [comment]
As discussed in the March-Session - should be allowed to give the download area a Name for better indication.

As I know in the meantime the Runtime SDK currently allows only to define a Name before the download (and not afterwards) so just make the text editable within the download Dialog, so that we could define a Name
Gerhard "Luigi"

**Comment by aeveland** [comment]
covered in 962

**Comment by aeveland** [comment]
For iOS we handle renaming via the overflow menu. No renaming upon creation of offline area.
