### ISSUE TITLE
GUIDs attributes are visible for related records

### ISSUE THREAD

**Issue by rashanjwalker** [doug-m/CollectorAuroraTesting#56]
### Issue

In Aurora, GUIDS are visible when viewing a related record.

### Expected Behavior
GUIDs should not be visible in the app.  

In the "Configure Attribute" setting in the web map, I also verified that the GUID field was not visible.

### Map and Credentials

* Group Name:  ESS_Testing_Rashan
* Map Name: Springs_QA_Version or Spring_Z_Val_QA_FS

### Steps to Reproduce
1.  Enable GLOBALIDs on a feature class to be used for the relationship class
2.  Created a guid attributes on tables and feature classes that will be related to the feature class in step#1
3.  Edit the related table or related feature class in Aurora
4.  Save and view the record.  The guid attribute will be visible in the app.

![image1](https://user-images.githubusercontent.com/38108384/38393651-52db6e9c-38e0-11e8-9b7e-7b85c7ec62ba.png)
![image2](https://user-images.githubusercontent.com/38108384/38393652-52f9ca18-38e0-11e8-919a-93b6beb5a70d.png)
![image3](https://user-images.githubusercontent.com/38108384/38393653-5311d130-38e0-11e8-90ec-2ea099a55f95.png)

### Device Information
* Device: iPhone 6+
* OS Version:11.2.6

**Comment by colinlawr** [comment]
Still reproducible in 2238 build.

**Comment by Kevin-GIS** [comment]
In ArcGIS Online, when configuring the popup for related tables, GUID fields are enabled for Display by default. Therefore they will be displayed in Collector-Aurora. 

Therefore in order for the popup to not display GUIDs, the field display should be disabled in the popup configuration in the webmap. 

This is expected behavior since Collector-Aurora honors the popup configuration settings from AGOL.
