### ISSUE TITLE
C20 - Related records in a table not shown (or overseen)

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#84]
Version: Build 2238
OS     : iPad Air 2, iOS 11.3.1

we have a map configured with Relates in Pro, after publish those are availible within the WebMap. Now try to edit features online in Collector,
but we didn't see the releated records as expected.

Maybe I oversee this or the additonal relates have a bad impact on the behavior.

Steps:
* Open ArcGIS Pro-Project
* Publish to ArcGIS Online with Sync enable
* Check Relates in MapViwer
* Open WebMap in Collector, identify one element or edit - expect to see the related records, but they didn't

see attached screenshots and data to repro the problem.

Gerhard "Luigi" trichtl
[bug.docx](https://github.com/doug-m/CollectorAuroraTesting/files/1992968/bug.docx)
[bug.txt](https://github.com/doug-m/CollectorAuroraTesting/files/1992969/bug.txt)
[C20.zip](https://github.com/doug-m/CollectorAuroraTesting/files/1992970/C20.zip)

**Comment by Kevin-GIS** [comment]
@trichtl I tested this issue and was able to reproduce it. However the problem is due to how the relationships were configured in the geodatabase in Pro and not directly an issue related to Collector. 

The relationship between the GE_MF50_GU_F polygon layer and the GE_GeologicUnit table is configured where the table is the origin and the polygon layer is the destination. In order for the relationship to be used in Collector, the origin must be a feature layer and not a table.

When I reversed that relationship and republished from Pro, the issue wasn't reproducible in Collector.
