### ISSUE TITLE
Estimated Vertical Accuracy field always populates with 3m

### ISSUE THREAD

**Issue by asmyrk** [doug-m/CollectorAuroraTesting#85]
### Issue
Vertical accuracy field always populates with the same number despite the horizontal accuracy jumping around.

### Expected Behavior
I know the vertical accuracy estimate is not correct because standing over my control, the vertical is anywhere from 20 to 60 meters off.  That is what I would expect on my cell phone so I'm not worried about that, but I would expect that field to then populate with a reasonable number and it always just says 3 meters.

### Map and Credentials

* Group Name:  Asset Repair
* Map Name: CollectorAurora

### Steps to Reproduce
Collect data in a 3D layer.

### Device Information
* Device:  iPhone 7
* OS Version: 11.3.1

**Comment by Kevin-GIS** [comment]
@asmyrk thanks for the feedback.

During your testing, when monitoring the horizontal and vertical accuracy values, was the vertical accuracy value always populated with a value or would it fluctuate between being blank and populated?

If so, when the value did become populated, it would be the same value each time. Correct?

I tested an iPhone 7 as well and noticed this behavior. In my case I was using feet. For the location I was at, the horizontal accuracy value always displayed and would keep changing. The vertical accuracy value was blank most of the time, but would populate with 13.1 feet each time. 

However when I tested the same workflow using an iPhone 5, the vertical accuracy wasn't constant, but would fluctuate between the same two values. 

In both cases I disabled Wi-Fi and used cellular/GPS. 

I think this issue is device/iOS related, given that its the built in location services supplying the values to Aurora, and based off my testing, it can be different per device.

**Comment by asmyrk** [comment]
Yes it populated every time with the same value even though the horizontal changed as expected.  Do you think this will be different then when we can connect an R1 or R2?

Thanks,

Ali’s

On May 17, 2018, at 1:07 PM, Kevin Burke <notifications@github.com<mailto:notifications@github.com>> wrote:


@asmyrk<https://github.com/asmyrk> thanks for the feedback.

During your testing, when monitoring the horizontal and vertical accuracy values, was the vertical accuracy value always populated with a value or would it fluctuate between being blank and populated?

If so, when the value did become populated, it would be the same value each time. Correct?

I tested an iPhone 7 as well and noticed this behavior. In my case I was using feet. For the location I was at, the horizontal accuracy value always displayed and would keep changing. The vertical accuracy value was blank most of the time, but would populate with 13.1 feet each time.

However when I tested the same workflow using an iPhone 5, the vertical accuracy wasn't constant, but would fluctuate between the same two values.

In both cases I disabled Wi-Fi and used cellular/GPS.

I think this issue is device/iOS related, given that its the built in location services supplying the values to Aurora, and based off my testing, it can be different per device.

**Comment by asmyrk** [comment]
Stupid phone autocorrect. I meant to sign my name Alison not Ali’s.

On May 18, 2018, at 8:15 AM, Alison Walker <alison@frontierprecision.com<mailto:alison@frontierprecision.com>> wrote:

Yes it populated every time with the same value even though the horizontal changed as expected.  Do you think this will be different then when we can connect an R1 or R2?

Thanks,

Ali’s

On May 17, 2018, at 1:07 PM, Kevin Burke <notifications@github.com<mailto:notifications@github.com>> wrote:


@asmyrk<https://github.com/asmyrk> thanks for the feedback.

During your testing, when monitoring the horizontal and vertical accuracy values, was the vertical accuracy value always populated with a value or would it fluctuate between being blank and populated?

If so, when the value did become populated, it would be the same value each time. Correct?

I tested an iPhone 7 as well and noticed this behavior. In my case I was using feet. For the location I was at, the horizontal accuracy value always displayed and would keep changing. The vertical accuracy value was blank most of the time, but would populate with 13.1 feet each time.

However when I tested the same workflow using an iPhone 5, the vertical accuracy wasn't constant, but would fluctuate between the same two values.

In both cases I disabled Wi-Fi and used cellular/GPS.

I think this issue is device/iOS related, given that its the built in location services supplying the values to Aurora, and based off my testing, it can be different per device.

**Comment by Kevin-GIS** [comment]
Thank you for the feedback @asmyrk. 

No this shouldn't be a problem using external receivers. Looks to be unique to the integrated receiver built-in to iOS devices.
