### ISSUE TITLE
Download error taking preplanned map offline

### ISSUE THREAD

**Issue by mschenker** [doug-m/CollectorAuroraTesting#97]
### Issue
I am exeriencing a download error taking a preplanned map (created in earlyadopters.mapsqa.arcgis.com using the UI) offline. The message "Download Error" appears at the end of the downlad process (when the "loading indicator" completes). Error message is "not found"

### Map and Credentials

* Group Name: CollectorAuroraIssueMatt1 (User Collector4ArcGIS not found in subscription but Group is open to all users)
* Map Name:SwitzerlandImageWebMercüöä

### Steps to Reproduce
Publish Webmap from ArcGIS Pro (use World Imagery basemap to avoid Known Issue with World Topo)
Enable Synch etc.
Define offline Area
Download Webmap in Collector

### Device Information
* Device: iOS
* OS Version:11.3.1

**Comment by mschenker** [comment]
Note: I will do some more testing to narrow down the cause, it could be the special characters that are the root of the issue.

**Comment by mschenker** [comment]
Tested without special characters (in name f webmap and featurelayer and map area), same error

**Comment by mschenker** [comment]
Same webmap (after deleting the preplanned area) displays a sign-in dialog while trying to create an ad-hoc offline area

**Comment by mschenker** [comment]
I just verified that this is caused by something in https://earlyadopters.mapsqa.arcgis.com. Publishing the same webmap (and map area) using a python script works in www.arcgis.com and fails in "mapsqa". Error as described above.

**Comment by Kevin-GIS** [comment]
Closing this issue as the behavior appears to have been unique to the QA environment used for this testing. 

The original issue potentially was due to the offline area being downloaded in Collector before the basemap or replica was fully generated through ArcGIS Online. 

In general, when working with preplanned areas, Collector now displays 'Generating...' for any preplanned area that is still getting built and prevents it from getting downloaded until its completed. Once all the necessary components of the offline area have been generated, it should be available for download in Collector.

**Comment by simongis** [comment]
I have encountered this exact issue with a 10.7.1 base deployment on Azure.  Have raised via Support channel.
